UniversitySystemGreyHat/Models/AssignCourseToTeacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversitySystemGreyHat.Models
{
    public class AssignCourseToTeacher
    {
        public int AssignCourseToTeacherId { get; set; }
        [Required(ErrorMessage = "Please select a department")]
        public int DepartmentId { get; set; }
        [Required(ErrorMessage = "Please select a teacher")]

        public int TeacherId { get; set; }
        [Required(ErrorMessage = "Please select a course")]

        public int CourseId { get; set; }
        public string Status { get; set; }
    }
}

UniversitySystemGreyHat/Models/ViewModel/CourseStatisticsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversitySystemGreyHat.Models.ViewModel
{
    public class CourseStatisticsViewModel
    {
        public int DepartmentId { get; set; }
       
        public string CourseCode { get; set; }
       
        public string CourseName { get; set; }
        public string SemesterName { get; set; }
        
        public string TeacherName { get; set; }
    }
}

UniversitySystemGreyHat/Controllers/AssignCourseToTeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversitySystemGreyHat.Gateway;
using UniversitySystemGreyHat.Manager;
using UniversitySystemGreyHat.Models;
using UniversitySystemGreyHat.Models.ViewModel;

namespace UniversitySystemGreyHat.Controllers
{
    public class AssignCourseToTeacherController : Controller
    {
        private DepartmentManager departmentManager;
        private CourseManager courseManager;
        private AssignCourseToTeacherManager assignCourseToTeacherManager;

        public AssignCourseToTeacherController()
        {
            departmentManager=new DepartmentManager();
            courseManager=new CourseManager();
            assignCourseToTeacherManager=new AssignCourseToTeacherManager();
        }
        // GET: AssignCourseToTeacher
        

        public JsonResult GetTacherByDepartmentId(int deptId)
        {
           List<TeacherViewModel> teacherViewModels= assignCourseToTeacherManager.GetTacherByDepartmentId(deptId);
            JsonResult jsonResult = Json(teacherViewModels);
            return jsonResult;

        }
        public JsonResult GetCourseByDepartmentId(int departId)
        {
            List<Course> courseList = assignCourseToTeacherManager.GetCourseByDepartmentId(departId);
            JsonResult jsonResult = Json(courseList);
            return jsonResult;

        }

        public JsonResult GetCredit(int teachrId)
        {
            TeacherViewModel teacherViewModel=assignCourseToTeacherManager.GetCredit(teachrId);
            JsonResult jsonResult = Json(teacherViewModel);
            return jsonResult;

        }
        public JsonResult GetTakenCredit(int teachrId)
        {
          
            TeacherViewModel takenCredit = assignCourseToTeacherManager.GetTakenCredit(teachrId);
            JsonResult jsonResult = Json(takenCredit);
            return jsonResult;

        }

        public ActionResult CourseStatistics()
        {
            ViewBag.Departments = courseManager.GetDepartmentsForDropDown();
            return View();
        }

        public JsonResult ViewCourseStatistics(int depttId)
        {
            List<CourseStatisticsViewModel> courseStatistics = assignCourseToTeacherManager.ViewCourseStatistics(depttId);
            JsonResult jsonResult = Json(courseStatistics);
            return jsonResult;
        }

    

        public JsonResult GetCourseByCourseId(int courseId)
        {
            Course courseList = assignCourseToTeacherManager.GetCourseByCourseId(courseId);
            JsonResult jsonResult = Json(courseList);
            return jsonResult;

        }

        [HttpGet]
        public ActionResult Save()
        {

            ViewBag.Departments = courseManager.GetDepartmentsForDropDown();
            return View();
        }

        [HttpPost]
        public ActionResult Save(AssignCourseToTeacher assign)
        {
            if (ModelState.IsValid)
            {
                assign.Status = "Assigned";
                string message = assignCourseToTeacherManager.Save(assign);
                ViewBag.Departments = courseManager.GetDepartmentsForDropDown();
                ViewBag.Message = message;
            }
            else
            {
                ViewBag.Departments = courseManager.GetDepartmentsForDropDown();
                ViewBag.Message = "Model State is Invalid";
                return View();
            }
           
                return View();
            }
           
    }
}

UniversitySystemGreyHat/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversitySystemGreyHat.Manager;
using UniversitySystemGreyHat.Models;

namespace UniversitySystemGreyHat.Controllers
{
    public class CourseController : Controller
    {
        private CourseManager courseManager;

        public CourseController()
        {
            courseManager=new CourseManager();
        }
        // GET: Course
        //public ActionResult Index()
        //{
        //    return View();
        //}

        //public ActionResult SaveCourse(Course course)
        //{
        //    string message = courseManager.Save(course);
        //    ViewBag.Message = message;
        //    return View();
        //}
        [HttpGet]
        public ActionResult SaveCourse()
        {
            ViewBag.semesters = courseManager.GetSemestersForDropDown();
            ViewBag.departments = courseManager.GetDepartmentsForDropDown();
            
            return View();
        }

        [HttpPost]
        public ActionResult SaveCourse(Course course)
        {
            
            if (ModelState.IsValid)
            {
               
                string message = courseManager.IsCourseNExists(course);
                ViewBag.Message = message;
                ViewBag.departments = courseManager.GetDepartmentsForDropDown();
                ViewBag.semesters = courseManager.GetSemestersForDropDown();
              
            }
            else
            {
                ViewBag.departments = courseManager.GetDepartmentsForDropDown();
                ViewBag.semesters = courseManager.GetSemestersForDropDown();
                ViewBag.Message = "Model State is Invalid";
                return View();
            }
            return View();
        }
    }
}

UniversitySystemGreyHat/Views/AssignCourseToTeacher/CourseStatistics.cshtml
@model UniversitySystemGreyHat.Models.Course


@{
    Layout = null;
    List<SelectListItem> departments = ViewBag.departments;
}

<!DOCTYPE html>

<html>
<head>
    <link href="~/StyleSheet/Nav.css" rel="stylesheet" />
    <style>
        .field-validation-error {
            color: red;
            font-family: 'Abel', sans-serif;
            font-size: 18px;
        }
        * {
            margin: 0;
            padding: 0;
        }

        html, body {
            height: 100%;
        }

        #courseStatisticsTable {
            font-family: 'Abel', sans-serif;
            border-collapse: collapse;
            width: 100%;
            font-size: 20px;
            
            display: inline-block;
        }

        #courseStatisticsTable td, #departmentTable th {
            border: 1px solid cornflowerblue;
            padding: 8px;
        }

        #courseStatisticsTable tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #courseStatisticsTable tr:hover {
            background-color: aquamarine;
        }

      

        .tablediv {
            width: 100%;
            height: 700px;
            background-color: red;
            position: absolute;
            margin-top: 2%;
            margin-left: 35%;
            display: inline-block;
        }


        .departmentName {
            margin-left: 9%;
         

        }
        .name {
            
            width: 300px;
            height: 35px;
            border: none;
            color: #000;
            padding-left: 15px;
            border-radius: 10px;
            border: 1px solid #0078ff;
            font-family: 'abel', sans-serif;
            font-size: 16px;
       
        }
       
    </style>
    <meta name="viewport" content="width=device-width"/>
    <link href="~/StyleSheet/table.css" rel="stylesheet" />


    <title>Course Statistics</title>
    <link rel="shortcut icon" type="/images/ico" href="/images/varsity.ico" />
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />

</head>
<body>
    <div class="header" id="home">
        <nav>
            <div class="logo">University Management</div>
            <ul>
                <li>
                    <a href="#">Department</a>
                    <ul>
                        <li style="height: 40px;"><a href='@Url.Action("Save", "Department")'>Save Department</a></li>
                        <li style="height: 55px;"><a href='@Url.Action("GetAllDepartments", "Department")'>View Departments</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">Course</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("SaveCourse", "Course")'>Save Course</a></li>
                        <li style="height: 40px;"><a href='@Url.Action("Save", "AssignCourseToTeacher")'>Assign Course</a></li>
                        <li style="height: 35px;"><a href='@Url.Action("CourseStatistics", "AssignCourseToTeacher")'>View Course Statics</a></li>
                        <li style="height: 45px;"><a href='@Url.Action("Save", "EnrollCourse")'>Enroll Course</a></li>
                    </ul>
                </li>
                <li><a href='@Url.Action("Save", "Teacher")'>Teacher</a></li>
                <li><a href='@Url.Action("Save", "RegisterStudent")'>Register Student</a></li>
                <li>
                    <a href="#">Allocate Class Room</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("Save", "ClassRoomAllocation")'>Class Room Allocation</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("ViewClassSchedule", "ClassRoomAllocation")'>View Class Schedule</a></li>
</ul>
                </li>
                <li>
                    <a href="#">Student Result</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("Save", "StudentResult")'>Save Student Result</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("ViewResult", "StudentResult")'>View Result</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">Unassign</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("UnAllocate", "UnAllocate")'>Unassign Room</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("Unassign", "UnassignCourses")'>Unassign Course</a></li>
                    </ul>
                </li>

                <li><a href='@Url.Action("Login", "Login")'>Logout</a></li>

            </ul>

        </nav>
    </div>
<div  id="tablediv" style="width: 70%; font-family: 'Abel', sans-serif; font-size: 18px; font-weight: bold; margin: 150px auto; ">

    
         
                @*@Html.Label("Department", "Department Name : ", new {@class = "departmentName"})*@


          
                @Html.DropDownList("DepartmentId", new SelectList(departments, "Value", "Text"), new {@style = "font-family: 'Abel', sans-serif; font-size: 18px;margin-top: 10px;margin-left: 35%;", @class = "name"})
                @Html.ValidationMessage("DepartmentId")


           
          
                    <table id="courseStatisticsTable" style="width: 700px; font-family: 'Abel', sans-serif; font-size: 18px; margin-left: 15%;margin-top:5% ">

                        <thead>
                            <tr>
                                <th style="width: 150px; height: 50px; background-color: lightseagreen; color: white;">Code</th>
                                <th style="width: 250px; height: 50px; background-color: lightseagreen; color: white; ">Name/Title</th>
                                <th style="width: 150px; height: 50px; background-color: lightseagreen; color: white; ">Semester</th>
                                <th style="width: 400px; height: 50px; background-color: lightseagreen; color: white; ">Assigned To</th>
                            </tr>
                        </thead>
                        <tbody id="CourseDetails"></tbody>
                    </table>

       

   




   



</div>
<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script>
    $(document).ready(function() {


        $('#DepartmentId').change(function() {

            var departmentId = $('#DepartmentId').val();

            var json = { depttId: departmentId };
            $.ajax({
                type: "POST",

                url: '@Url.Action("ViewCourseStatistics", "AssignCourseToTeacher")',


                contentType: "application/json; charset=utf-8",

                data: JSON.stringify(json),

                success: function(data) {
                    $('#CourseDetails').empty();
                    //$("#DepartmentId").append('<option value="">--Select--</option>');
                    $.each(data, function(key, value) {


                        $("#CourseDetails").append('<tr> <th>' + value.CourseCode + '</th> <th>' + value.CourseName + '</th> <th>' + value.SemesterName + '</th> <th>' + value.TeacherName + '</th></tr>');
                    });


                }
            });


        });
    });


</script>

@*<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $('#courseStatisticsTable').DataTable();
    });
</script>*@

</body>
</html>