UniversitySystemGreyHat/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversitySystemGreyHat.Manager;
using UniversitySystemGreyHat.Models;

namespace UniversitySystemGreyHat.Controllers
{
    public class CourseController : Controller
    {
        private CourseManager courseManager;

        public CourseController()
        {
            courseManager=new CourseManager();
        }
        // GET: Course
        //public ActionResult Index()
        //{
        //    return View();
        //}

        //public ActionResult SaveCourse(Course course)
        //{
        //    string message = courseManager.Save(course);
        //    ViewBag.Message = message;
        //    return View();
        //}
        [HttpGet]
        public ActionResult SaveCourse()
        {
            ViewBag.semesters = courseManager.GetSemestersForDropDown();
            ViewBag.departments = courseManager.GetDepartmentsForDropDown();
            
            return View();
        }

        [HttpPost]
        public ActionResult SaveCourse(Course course)
        {
            
            if (ModelState.IsValid)
            {
               
                string message = courseManager.IsCourseNExists(course);
                ViewBag.Message = message;
                ViewBag.departments = courseManager.GetDepartmentsForDropDown();
                ViewBag.semesters = courseManager.GetSemestersForDropDown();
              
            }
            else
            {
                ViewBag.departments = courseManager.GetDepartmentsForDropDown();
                ViewBag.semesters = courseManager.GetSemestersForDropDown();
                ViewBag.Message = "Model State is Invalid";
                return View();
            }
            return View();
        }
    }
}

UniversitySystemGreyHat/Controllers/RegisterStudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementWebApp.Manager;
using UniversityManagementWebApp.Models;
using UniversityManagementWebApp.Models.ViewModel;
using UniversitySystemGreyHat.Models.ViewModel;

namespace UniversityManagementWebApp.Controllers
{
    public class RegisterStudentController : Controller
    {
        private StudentViewModel studentViewModel;
        private StudentModel studentModel;
        private StudentManager studentManager;

        public RegisterStudentController()
        {
            studentManager = new StudentManager();
            studentModel = new StudentModel();
            studentViewModel = new StudentViewModel();
        }
        //
        // GET: /RegisterStudent/
        [HttpGet]
        public ActionResult Save(string departmentName,StudentViewModel studentViewModel)
        {
            List<StudentViewModel> studentViewModels = studentManager.GetAllDepartments();
            ViewBag.Departments = studentViewModels;
           

            return View();
        }
        [HttpPost]
        public ActionResult Save(StudentModel studentModel)
        {
            
            if (ModelState.IsValid)
            {
                List<StudentViewModel> studentViewModels = studentManager.GetAllDepartments();
                ViewBag.Departments = studentViewModels;

                ViewBag.Save = studentManager.Save(studentModel);
               ViewBag.StudentInfo = studentManager.GetStudentInfo(studentModel);

            }
            else
            {
                List<StudentViewModel> studentViewModels = studentManager.GetAllDepartments();
                ViewBag.Departments = studentViewModels;
                ViewBag.Message = "Model State is Invalid";
                return View();
            }
            return View();
        }

        public JsonResult GetCredit(string department, int departmentId)
        {
            StudentModel studentViewModels = studentManager.IdGenerate(department, departmentId);
            JsonResult jsonResult = Json(studentViewModels);
            return jsonResult;

        }
    }
}

UniversitySystemGreyHat/Views/RegisterStudent/Save.cshtml
@using UniversityManagementWebApp.Models.ViewModel
@model UniversityManagementWebApp.Models.StudentModel
@{
    Layout = null;
    List<StudentViewModel> departmentList = ViewBag.Departments;
    List<StudentViewModel> studentInfo = ViewBag.StudentInfo;

}

<!DOCTYPE html>

<html>
<head>
    <link href="~/StyleSheet/Nav.css" rel="stylesheet" />
    <style>
        .field-validation-error {
            color: red;
            font-family: 'Abel', sans-serif;
            font-size: 18px;
        }
        * {
            margin: 0;
            padding: 0;
        }

        html, body {
            height: 100%;
        }
        .Department {
            width: 300px;
            height: 35px;
            border: none;
            color: #000;
            padding-left: 5px;
            border-radius: 10px;
            border: 1px solid #0078ff;
            font-family: 'abel', sans-serif;
            font-size: 16px;
        }

        .RegistrationNo {
            width: 300px;
            height: 35px;
            border: none;
            color: #000;
            padding-left: 5px;
            border-radius: 10px;
            border: 1px solid #0078ff;
            font-family: 'abel', sans-serif;
            font-size: 16px;
        }

        #studentTable {
            margin-left: 30%;
            margin-top: 6%;
        }

            #studentTable td {
                width: 150px;
            }

            #studentTable tr {
                height: 45px;
            }

        .Name {
            width: 300px;
            height: 35px;
            border: none;
            color: #000;
            padding-left: 5px;
            border-radius: 10px;
            border: 1px solid #0078ff;
            font-family: 'abel', sans-serif;
            font-size: 16px;
        }

        .Email {
            width: 300px;
            height: 35px;
            border: none;
            color: #000;
            padding-left: 5px;
            border-radius: 10px;
            border: 1px solid #0078ff;
            font-family: 'abel', sans-serif;
            font-size: 16px;
        }

        .ContactNo {
            width: 300px;
            height: 35px;
            border: none;
            color: #000;
            padding-left: 5px;
            border-radius: 10px;
            border: 1px solid #0078ff;
            font-family: 'abel', sans-serif;
            font-size: 16px;
        }

        .Date {
            width: 300px;
            height: 35px;
            border: none;
            color: #000;
            padding-left: 5px;
            border-radius: 10px;
            border: 1px solid #0078ff;
            font-family: 'abel', sans-serif;
            font-size: 16px;
        }

        .Address {
            width: 300px;
            height: 60px;
            border: none;
            color: #000;
            padding-left: 5px;
            border-radius: 10px;
            border: 1px solid #0078ff;
            font-family: 'abel', sans-serif;
            font-size: 16px;
        }

        ::-webkit-input-placeholder {
            color: #000;
            font-size: 16px;
            letter-spacing: 2px;
            padding-left: 10px;
        }

        #save {
            margin-top: 10px;
            margin-left: 68%;
            height: 36px;
            width: 100px;
            background: dodgerblue;
            color: #fff;
            border: none;
            border: 1px solid black;
            border-radius: 6px;
            font-family: 'Abel';
            letter-spacing: .2em;
            font-size: 18px;
            font-weight: bold;
            text-align: center;
        }

        #save:hover {
            background-color: #0078ff;
        }
    </style>
    <meta name="viewport" content="width=device-width" />
    <title>Save Student</title>
    <link rel="shortcut icon" type="/images/ico" href="/images/varsity.ico" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
</head>
<body>
    <div class="header" id="home">
        <nav>
            <div class="logo">University Management</div>
            <ul>
                <li>
                    <a href="#">Department</a>
                    <ul>
                        <li style="height: 40px;"><a href='@Url.Action("Save", "Department")'>Save Department</a></li>
                        <li style="height: 55px;"><a href='@Url.Action("GetAllDepartments", "Department")'>View Departments</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">Course</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("SaveCourse", "Course")'>Save Course</a></li>
                        <li style="height: 40px;"><a href='@Url.Action("Save", "AssignCourseToTeacher")'>Assign Course</a></li>
                        <li style="height: 35px;"><a href='@Url.Action("CourseStatistics", "AssignCourseToTeacher")'>View Course Statics</a></li>
                        <li style="height: 45px;"><a href='@Url.Action("Save", "EnrollCourse")'>Enroll Course</a></li>
                    </ul>
                </li>
                <li><a href='@Url.Action("Save", "Teacher")'>Teacher</a></li>
                <li><a href='@Url.Action("Save", "RegisterStudent")'>Register Student</a></li>
                <li>
                    <a href="#">Allocate Class Room</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("Save", "ClassRoomAllocation")'>Class Room Allocation</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("ViewClassSchedule", "ClassRoomAllocation")'>View Class Schedule</a></li>
   </ul>
                </li>
                <li>
                    <a href="#">Student Result</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("Save", "StudentResult")'>Save Student Result</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("ViewResult", "StudentResult")'>View Result</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">Unassign</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("UnAllocate", "UnAllocate")'>Unassign Room</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("Unassign", "UnassignCourses")'>Unassign Course</a></li>
                    </ul>
                </li>

                <li><a href='@Url.Action("Login", "Login")'>Logout</a></li>

            </ul>

        </nav>
    </div>
<div style="font-family: 'Abel', sans-serif; font-size: 18px;">

    <form method="POST" style="margin-top:10%;">
        <table id="studentTable">
           
          
            <tr>
                <td>@Html.Label("Name", "Name :")</td>
                <td>
                    @Html.TextBoxFor(x => x.Name, new { @class = "Name", @placeholder = "Enter Student Name" })
                    @Html.ValidationMessageFor(x => x.Name)





                </td>


            </tr>
            <tr>
                <td>@Html.Label("Email", "Email :")</td>
                <td>
                    @Html.TextBoxFor(x => x.Email, new { @class = "Email", @placeholder = "Enter Email" })

                    @Html.ValidationMessageFor(x => x.Email)




                </td>


            </tr>
            <tr>
                <td>@Html.Label("ContactNo", "Contact No :")</td>
                <td>
                    @Html.TextBoxFor(x => x.ContactNo, new { @class = "ContactNo", @placeholder = "Enter Contact No." })
                    @Html.ValidationMessageFor(x => x.ContactNo)





                </td>


            </tr>
            <tr>
                <td>@Html.Label("Date", "Date :")</td>
                <td>
                    @Html.TextBoxFor(x => x.Date, new { @class = "Date" })
                    @Html.ValidationMessageFor(x => x.Date)
                </td>


            </tr>
            <tr>
                <td>@Html.Label("Address", "Address :")</td>
                <td>
                    @Html.TextAreaFor(x => x.Address, 5, 30, new { @class = "Address", @placeholder = "Enter Address" })
                    @Html.ValidationMessageFor(x => x.Address)
                </td>


            </tr>
            <tr>
                <td>@Html.Label("DepartmentId", "Department Name :")</td>
                <td>
                    @Html.DropDownListFor(x => x.DepartmentId, new SelectList(departmentList, "DepartmentId", "DepartmentCode"), "--Select a department--", new { @class = "Department" })


                    @Html.ValidationMessageFor(x => x.DepartmentId)

                </td>
            </tr>
            <tr>
                <td>
                    @Html.Label("RegistrationNo", "Registration No. :")
                </td>

                <td>
                    @Html.TextBoxFor(x => x.RegistrationNo, new { @class = "RegistrationNo", @placeholder = "Enter Registration No.", @readonly = "readOnly" })

                    @Html.ValidationMessageFor(x => x.RegistrationNo)


                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" id="save" name="save" value="Submit" />
                </td>
            </tr>


            <tr>
                <td></td>
                <td>
                    @if (ViewBag.Save == "Save Successfully")
                    {
                        <label id="messageLabl" name="messageLabl" style="color: green; font-family: 'Abel', sans-serif; font-size: 18px;">@ViewBag.Save </label>



                    }
                    else
                    {
                        <label id="messageLabl" name="messageLabl" style="color: red; font-family: 'Abel', sans-serif; font-size: 18px;">@ViewBag.Save </label>

                    }
                </td>
            </tr>

        </table>

    </form>
@*<form method="POST">
    <div style="width: auto; position: absolute; margin-left: 28%;">

        <table>
            @if (studentInfo != null)
            {
                <tr>Department Name :</tr>
                <br/>
                <tr>Registration No.</tr>
                <br/>

                <tr>Name :</tr>
                <br/>

                <tr>Email :</tr>
                <br/>

                <tr>Contact No :</tr>
                <br/>

                <tr>Date :</tr>
                <br/>

                <tr>Address :</tr>
                <br/>
            }
        </table>
    </div>*@
    <div style="width: auto; margin-left: 42%;">
        <table style="width: 500px; margin-left: 120px; position: relative;">
            @if (studentInfo != null)
            {

                foreach (var students in studentInfo)
                {
                    <tr>@students.DepartmentCode</tr>
                    <br/>

                    <tr>@students.RegistrationNo</tr>
                    <br/>
                    <tr>@students.Name</tr>
                    <br/>
                    <tr>@students.Email</tr>
                    <br/>
                    <tr>@students.ContactNo</tr>
                    <br/>
                    <tr>@students.Date</tr>
                    <br/>
                    <tr>@students.Address</tr>
                }
            }



        </table>
    </div>

</form>




</div>

<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script>
    $(document).ready(function() {

        $('#DepartmentId').change(function() {


            if ($('#DepartmentId :selected').text() === "--Select a department--") {
                $("#RegistrationNo").hide();
            } else {
                $("#RegistrationNo").show();
            }
            var departmentCode = $('#DepartmentId :selected').text();
            var departmentId = $('#DepartmentId').val();


            var json = { department: departmentCode, departmentId: departmentId };


            $.ajax({
                type: "POST",

                url: '@Url.Action("GetCredit", "RegisterStudent")',


                contentType: "application/json; charset=utf-8",

                data: JSON.stringify(json),

                success: function(data) {
                    //$("#RegistrationNo").empty();


                    $("#RegistrationNo").val(data.RegistrationNo);

                    // $("#TakenCredit").append('<input type="text" value=' + value.TakenCredit + ' />');

                    //$("#StudentDetails").append('<tr> <td>'+value.StudentName+'</td>   <td>'+value.Address+'</td>   <td>'+value.DepartmentName+'</td></tr>');


                }
            });


        });
    });
</script>

<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<script>
    $(function() {
            $("#Date").datepicker();
        }
    );
</script>

<script>
    $(document).ready(function() {
        var d = new Date(),
            date = ((d.getMonth() + 1) + '/' + (d.getDate()) + '/' + d.getFullYear());
        $('#Date').val(date);
    });
</script>
</body>
</html>