UniversitySystemGreyHat/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.UI.WebControls;

namespace UniversitySystemGreyHat.Models
{
    public class Department
    {
        public int DepartmentId { get; set; }

        [Required(ErrorMessage = "Please provide Department Code")]
        

        [DisplayName("Code")]
        public string DepartmentCode { get; set; }


        [Required(ErrorMessage = "Please provide Department Name")]
        [DisplayName("Name")]
        public string DepartmentName { get; set; }

    }

     //[Required(ErrorMessage = "An Album Title is required")]
     //   [DisplayFormat(ConvertEmptyStringToNull = false)]
     //   [StringLength(160, MinimumLength = 2)]
     //   public string Title { get; set; }

     //   [Range(0.01, 100.00, ErrorMessage = "Price must be between 0.01 and 100.00")]
     //   [DataType(DataType.Currency)]
     //   public decimal Price { get; set; }

     //   [DisplayName("Album Art URL")]
     //   [DataType(DataType.ImageUrl)]
     //   [StringLength(1024)]
}

UniversitySystemGreyHat/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversitySystemGreyHat.Manager;
using UniversitySystemGreyHat.Models;

namespace UniversitySystemGreyHat.Controllers
{
    public class CourseController : Controller
    {
        private CourseManager courseManager;

        public CourseController()
        {
            courseManager=new CourseManager();
        }
        // GET: Course
        //public ActionResult Index()
        //{
        //    return View();
        //}

        //public ActionResult SaveCourse(Course course)
        //{
        //    string message = courseManager.Save(course);
        //    ViewBag.Message = message;
        //    return View();
        //}
        [HttpGet]
        public ActionResult SaveCourse()
        {
            ViewBag.semesters = courseManager.GetSemestersForDropDown();
            ViewBag.departments = courseManager.GetDepartmentsForDropDown();
            
            return View();
        }

        [HttpPost]
        public ActionResult SaveCourse(Course course)
        {
            
            if (ModelState.IsValid)
            {
               
                string message = courseManager.IsCourseNExists(course);
                ViewBag.Message = message;
                ViewBag.departments = courseManager.GetDepartmentsForDropDown();
                ViewBag.semesters = courseManager.GetSemestersForDropDown();
              
            }
            else
            {
                ViewBag.departments = courseManager.GetDepartmentsForDropDown();
                ViewBag.semesters = courseManager.GetSemestersForDropDown();
                ViewBag.Message = "Model State is Invalid";
                return View();
            }
            return View();
        }
    }
}

UniversitySystemGreyHat/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversitySystemGreyHat.Manager;
using UniversitySystemGreyHat.Models;

namespace UniversitySystemGreyHat.Controllers
{
    public class DepartmentController : Controller
    {
        private DepartmentManager departmentManager;

        public DepartmentController()
        {
            departmentManager = new DepartmentManager();
        }

        // GET: Department

        [HttpGet]
        public ActionResult Save()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(Department department)
        {
            if (ModelState.IsValid)
            {
                string message = departmentManager.Save(department);
                ViewBag.Message = message;

            }
            else
            {
                ViewBag.Message = "Model State is Invalid";
                return View();
            }
            return View();
        }
    

    public ActionResult GetAllDepartments()
        {

            List<Department> departmentList = departmentManager.GetAllDepartments();
            return View(departmentList);
        }
    }
}

UniversitySystemGreyHat/Views/Department/GetAllDepartments.cshtml
@using UniversitySystemGreyHat.Models
@model List<UniversitySystemGreyHat.Models.Department>
@{
    Layout =null;
}
<!DOCTYPE html>

<html>
<head>
    <link href="~/StyleSheet/Nav.css" rel="stylesheet" />
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        html, body {
           
            height: 100%;
        }

      
         .field-validation-error {
             color: red;
             font-family: 'Abel', sans-serif;
             font-size: 18px;
         }

        #departments {
            font-family: 'Abel', sans-serif;
            border-collapse: collapse;
            width: 100%;
            font-size: 20px;
            display: inline-block;
        }

            #departments td, #departments th {
                border: 1px solid cornflowerblue;
                padding: 8px;
            }

            #departments tr:nth-child(even) {
                background-color: #f2f2f2;
            }

            #departments tr:hover {
                background-color: aquamarine;
            }

      
        
    </style>
    <meta name="viewport" content="width=device-width"/>
    <title>View All Departments</title>
    <link rel="shortcut icon" type="/images/ico" href="/images/varsity.ico" />
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet"/>
</head>
<body>
    <div id="home">
        <nav>
            <div class="logo">University Management</div>
            <ul>
                <li>
                    <a href="#">Department</a>
                    <ul>
                        <li style="height: 40px;"><a href='@Url.Action("Save", "Department")'>Save Department</a></li>
                        <li style="height: 55px;"><a href='@Url.Action("GetAllDepartments", "Department")'>View Departments</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">Course</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("SaveCourse", "Course")'>Save Course</a></li>
                        <li style="height: 40px;"><a href='@Url.Action("Save", "AssignCourseToTeacher")'>Assign Course</a></li>
                        <li style="height: 35px;"><a href='@Url.Action("CourseStatistics", "AssignCourseToTeacher")'>View Course Statics</a></li>
                        <li style="height: 45px;"><a href='@Url.Action("Save", "EnrollCourse")'>Enroll Course</a></li>
                    </ul>
                </li>
                <li><a href='@Url.Action("Save", "Teacher")'>Teacher</a></li>
                <li><a href='@Url.Action("Save", "RegisterStudent")'>Register Student</a></li>
                <li>
                    <a href="#">Allocate Class Room</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("Save", "ClassRoomAllocation")'>Class Room Allocation</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("ViewClassSchedule", "ClassRoomAllocation")'>View Class Schedule</a></li>
     </ul>
                </li>
                <li>
                    <a href="#">Student Result</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("Save", "StudentResult")'>Save Student Result</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("ViewResult", "StudentResult")'>View Result</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">Unassign</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("UnAllocate", "UnAllocate")'>Unassign Room</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("Unassign", "UnassignCourses")'>Unassign Course</a></li>
                    </ul>
                </li>
                <li><a href='@Url.Action("Login", "Login")'>Logout</a></li>


            </ul>

        </nav>
    </div>
        <div class="tablediv" style="width: 70%; margin: 8% auto; font-family: 'Abel', sans-serif; font-size: 18px; font-weight: bold; ">
            <table id="departments" class="departmentTable" style="width: 100%;  text-align: center; margin-top: 5%; margin-left: 8%; ">
                <thead style="background-color: #015965; color: white">
                <td style="height: 35px; width: 250px; background-color: lightseagreen; color: white;">Code</td>
                <td style="height: 35px; width: 550px; background-color: lightseagreen; color: white;">Name</td>

                </thead>


                @foreach (Department department in Model)
                {
                    <tr>
                        <td style="height: 35px;">
                            @department.DepartmentCode
                        </td>
                        <td style="height: 35px;">
                            @department.DepartmentName
                        </td>
                    </tr>



                }

            </table>
            @*<script src="~/Scripts/jquery-1.12.4.min.js"></script>
            <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
            <script>


                $(document).ready(function () {
                    $('#departments').DataTable();
                });
            </script>*@

        </div>
   

</body>
</html>

UniversitySystemGreyHat/Views/Department/Save.cshtml
@using System.Web.UI.WebControls
@model UniversitySystemGreyHat.Models.Department
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <style>
        .field-validation-error {
            color: red;
            font-family: 'Abel', sans-serif;
            font-size: 18px;
        }
        * {
            margin: 0;
            padding: 0;
        }

        html, body {
            height: 100%;
        }
    </style>
    <meta name="viewport" content="width=device-width"/>
    <link rel="shortcut icon" type="/images/ico" href="/images/varsity.ico" />
    <title>Save Department</title>
    <link href="~/StyleSheet/Nav.css" rel="stylesheet" />
    <style>
        label.error {
              color: red;
          }
        .field-validation-error {
            color: red;
            font-family: 'Abel', sans-serif;
            font-size: 18px;
        }
        #departmentTable {
            margin-left: 30%;
            margin-top: 8%;
        }
        #departmentTable td {
            width: 150px;
        }#departmentTable tr {
            height: 50px;
        }
        .departmentCode {
            width: 300px;
            height: 35px;
            border: none;
            color: #000;
            padding-left: 5px;
            border-radius: 10px;
            border: 1px solid #0078ff;
            font-family: 'abel', sans-serif;
           
            font-size: 16px;
        }
        ::-webkit-input-placeholder {
            color: #000;
            font-size: 16px;
            letter-spacing: 2px;
            padding-left: 10px;
        }
        .departmentName {
            width: 300px;
            height: 35px;
            border: none;
            color: #000;
            padding-left: 5px;
            border-radius: 10px;
            border: 1px solid #0078ff;
            font-family: 'abel', sans-serif;
            font-size: 16px;
        }
        .saveBtn {
            margin-top: 10px;
            margin-left: 60%;
            height: 36px;
            width: 100px;
            background: dodgerblue;
            color: #fff;
            border: none;
            border: 1px solid black;
            border-radius: 6px;
            font-family: 'Abel';
            letter-spacing: .2em;
            font-size: 18px;
            font-weight: bold;
            text-align: center;
        }
            .saveBtn:hover {
                background-color: #DFFFFF;
            }
    </style>
</head>
<body>
  
    <div class="header" id="home">
        <nav>
            <div class="logo"></div>
            <ul>
                <li><a href="#">Department</a>
                    <ul>
                        <li style="height: 40px;"><a href='@Url.Action("Save", "Department")'>Save Department</a></li>
                        <li style="height: 55px;"><a href='@Url.Action("GetAllDepartments", "Department")'>View Departments</a></li>
                    </ul>
                </li>
                <li><a href="#">Course</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("SaveCourse", "Course")'>Save Course</a></li>
                        <li style="height: 40px;"><a href='@Url.Action("Save", "AssignCourseToTeacher")'>Assign Course</a></li>
                        <li style="height: 35px;"><a href='@Url.Action("CourseStatistics", "AssignCourseToTeacher")'>View Course Statics</a></li>
                        <li style="height: 45px;"><a href='@Url.Action("Save", "EnrollCourse")'>Enroll Course</a></li>
                    </ul>
                </li>
                <li><a href='@Url.Action("Save", "Teacher")'>Teacher</a></li>
                <li><a href='@Url.Action("Save", "RegisterStudent")'>Register Student</a></li>
                <li><a href="#">Allocate Class Room</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("Save", "ClassRoomAllocation")'>Class Room Allocation</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("ViewClassSchedule", "ClassRoomAllocation")'>View Class Schedule</a></li>
    </ul>
                </li>
                <li><a href="#">Student Result</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("Save", "StudentResult")'>Save Student Result</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("ViewResult", "StudentResult")'>View Result</a></li>
                    </ul></li>
                <li><a href="#">Unassign</a>
                    <ul>
                        <li style="height: 35px;"><a href='@Url.Action("UnAllocate", "UnAllocate")'>Unassign Room</a></li>
                        <li style="height: 50px;"><a href='@Url.Action("Unassign", "UnassignCourses")'>Unassign Course</a></li>
                    </ul>
                </li>

                <li><a href='@Url.Action("Login", "Login")'>Logout</a></li>

            </ul>

        </nav>
    </div>
<div style="font-family: 'Abel', sans-serif; font-size: 18px; margin-top: 10%;">
    @*@*<input type="button" value="Some text" onclick="@("window.location.href='" + @Url.Action("GetAllDepartments", "Department") + "'");" />*@
    @*<a href='@Url.Action("GetAllDepartments", "Department")'>
        @*<input type="button" value="Redirect"/>*@ @*View Departments*@
    @*</a>*@
    <form id="signupForm" method="POST">
        <table id="departmentTable">
            <tr>
                <td style="width: 150px;">@Html.LabelFor(x => x.DepartmentCode, "Department Code :", new {@class = "departmentCodeLabel"})</td>
                <td>@Html.TextBoxFor(x => x.DepartmentCode, new {@class = "departmentCode", @placeholder = "Enter Department Code"})
                    @Html.ValidationMessageFor(x => x.DepartmentCode)</td>



            </tr>

            <tr>
                <td>@Html.LabelFor(x => x.DepartmentName, "Department Name :")</td>
                <td>@Html.TextBoxFor(x => x.DepartmentName, new {@class = "departmentName", @placeholder = "Enter Department Name"})
                    @Html.ValidationMessageFor(x => x.DepartmentName)</td>

            </tr>

            <tr>
                <td></td>
                <td> <input type="submit" value="Save" class="saveBtn" style="font-family: 'Abel', sans-serif; font-size: 18px; width: 120px"/>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    @if (ViewBag.Message != null)
                    {
                        <label style="font-family: 'Abel', sans-serif; font-size: 18px;">@ViewBag.Message</label>
                    }
                </td>
            </tr>

            @*<tr>
                <input type="button" value="Some text" onclick="@("window.location.href='" + @Url.Action("GetAllDepartments", "Department") + "'");" />
            </tr>*@

        </table>


        <script src="~/Scripts/jquery-1.12.4.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>


    </form>


</div>
</body>
</html>